### ISSUE TITLE
must match wasm-bindgen versions exactly

### ISSUE THREAD

**Issue by xmclark** [rustwasm/wasm-pack#272] opened 2018-08-28 00:46 UTC
## 🐛 Bug description
wasm-pack does not do what I expect when choosing to install wasm-bindgen. wasm-pack requires the version of wasm-bindgen installed and the one specified in the application's Cargo.toml to match exactly. A package with a partial version (e.g. 0.2 or 1) do not match liberally with an installed version of wasm-bindgen.

#### 🤔 Expected Behavior
I would expect the partial version to match liberally. Specifying a version of "1" would match 1 := 1.x.x := >=1.0.0 <2.0.0. 

#### 👟 Steps to reproduce

1. Install 0.2.17 of wasm-bindgen
2. Checkout master. 
3. Make a local test project that does wasm-bindgen stuff. 
4. Set the version of wasm-bindgen in Cargo.toml to "0.2"
5. Run wasm-pack on the directory

The wasm-bindgen binary will not be found and it will begin installing one. 

Switch the installed version to "0.2.17". 

It finds the globally installed instance. It works.

#### 🌍 Your environment
Include the relevant details of your environment.
wasm-pack version: d5bf5a3ecd676a214cc395c8d824180e7e68638c
rustc version: rustc 1.30.0-nightly (33b923fd4 2018-08-18)

**Comment by fitzgen** [comment] 2018-08-28 18:00
We must match the wasm-bindgen version used to in `cargo build` exactly (ish) and the way to do that properly is #270. That will also allow cargo to choose a semver compatible version of wasm-bindgen, and also for wasm-pack to use that exact version.

Going to close this as a duplicate of that issue -- thanks for taking the time to file an issue!

**Closed** 2018-08-28 18:00 UTC
