### ISSUE TITLE
[Call for help] Uncaught TypeError: Cannot read property '<function name>' of undefined

### ISSUE THREAD

**Issue by leonwanghui** [rustwasm/wasm-pack#710] opened 2019-09-04 02:17 UTC
## 🐛 Bug description
Recently I'm working on generate javascript code from rust using `wasm-pack`, but it seems that something went wrong when I pack the js code with `webpack`, and the errors is shown below:
```shell
index.js:84 Uncaught (in promise) TypeError: WebAssembly.instantiate(): Argument 0 must be a buffer source
    at e (index.js:84)
    at Object.<anonymous> (index.js:16)
    at t (index.js:4)
    at index.js:12
    at index.js:13
```

#### 🤔 Expected Behavior
Run well with no errors.

#### 👟 Steps to reproduce
Clear steps describing how to reproduce the issue, including commands and flags run. If you are seeing an error, please include the full error message and stack trace.

#### 🌍 Your environment
Include the relevant details of your environment.
wasm-pack version: `0.8.1`
rustc version: rustc 1.37.0 (eae3437df 2019-08-13)

**Comment by leonwanghui** [comment] 2019-09-04 02:24
Something interesting is when I try to run the function using `node`, everything works fine as below:
```shell
node src/osc_runtime_node.js 
{"kind":"ComputeResource","operation":"create","params":{"name":"nothing","size":1}}
```

* src/osc_runtime_node.js
```js
var engine = require("../runtime-engine/nodejs/runtime_engine");

var data = {
    kind: "ComputeResource",
    metadata: {
        operation: "create",
        cloud_provider: "hwcloud",
        labels: "test"
    },
    spec: {
        name: "nothing",
        size: 1
    }
};
var output = engine.load_resource_to_js(data);
var jsonData = JSON.stringify(output);
console.log(jsonData);
```

* runtime-engine/nodejs/runtime_engine.js
```js
let wasm;
const { TextDecoder } = require(String.raw`util`);

const heap = new Array(32);

heap.fill(undefined);

heap.push(undefined, null, true, false);

let stack_pointer = 32;

function addBorrowedObject(obj) {
    if (stack_pointer == 1) throw new Error('out of js stack');
    heap[--stack_pointer] = obj;
    return stack_pointer;
}

function getObject(idx) { return heap[idx]; }

let heap_next = heap.length;

function dropObject(idx) {
    if (idx < 36) return;
    heap[idx] = heap_next;
    heap_next = idx;
}

function takeObject(idx) {
    const ret = getObject(idx);
    dropObject(idx);
    return ret;
}
/**
* @param {any} value
* @returns {any}
*/
module.exports.load_resource_to_js = function(value) {
    try {
        const ret = wasm.load_resource_to_js(addBorrowedObject(value));
        return takeObject(ret);
    } finally {
        heap[stack_pointer++] = undefined;
    }
};

let WASM_VECTOR_LEN = 0;

let cachegetNodeBufferMemory = null;
function getNodeBufferMemory() {
    if (cachegetNodeBufferMemory === null || cachegetNodeBufferMemory.buffer !== wasm.memory.buffer) {
        cachegetNodeBufferMemory = Buffer.from(wasm.memory.buffer);
    }
    return cachegetNodeBufferMemory;
}

function passStringToWasm(arg) {

    const size = Buffer.byteLength(arg);
    const ptr = wasm.__wbindgen_malloc(size);
    getNodeBufferMemory().write(arg, ptr, size);
    WASM_VECTOR_LEN = size;
    return ptr;
}

let cachegetInt32Memory = null;
function getInt32Memory() {
    if (cachegetInt32Memory === null || cachegetInt32Memory.buffer !== wasm.memory.buffer) {
        cachegetInt32Memory = new Int32Array(wasm.memory.buffer);
    }
    return cachegetInt32Memory;
}

let cachedTextDecoder = new TextDecoder('utf-8');

let cachegetUint8Memory = null;
function getUint8Memory() {
    if (cachegetUint8Memory === null || cachegetUint8Memory.buffer !== wasm.memory.buffer) {
        cachegetUint8Memory = new Uint8Array(wasm.memory.buffer);
    }
    return cachegetUint8Memory;
}

function getStringFromWasm(ptr, len) {
    return cachedTextDecoder.decode(getUint8Memory().subarray(ptr, ptr + len));
}

function addHeapObject(obj) {
    if (heap_next === heap.length) heap.push(heap.length + 1);
    const idx = heap_next;
    heap_next = heap[idx];

    heap[idx] = obj;
    return idx;
}

module.exports.__wbindgen_json_serialize = function(arg0, arg1) {
    const ret = JSON.stringify(getObject(arg1));
    const ret0 = passStringToWasm(ret);
    const ret1 = WASM_VECTOR_LEN;
    getInt32Memory()[arg0 / 4 + 0] = ret0;
    getInt32Memory()[arg0 / 4 + 1] = ret1;
};

module.exports.__wbindgen_json_parse = function(arg0, arg1) {
    const ret = JSON.parse(getStringFromWasm(arg0, arg1));
    return addHeapObject(ret);
};
wasm = require('./runtime_engine_bg');
```

* runtime-engine/nodejs/runtime_engine_bg.js
```js
const path = require('path').join(__dirname, 'runtime_engine_bg.wasm');
const bytes = require('fs').readFileSync(path);
let imports = {};
imports['./runtime_engine.js'] = require('./runtime_engine.js');

const wasmModule = new WebAssembly.Module(bytes);
const wasmInstance = new WebAssembly.Instance(wasmModule, imports);
module.exports = wasmInstance.exports;
```

**Comment by leonwanghui** [comment] 2019-09-04 03:32
Made some code changes for the framework and the former error disappear but with some new errors below:
```shell
runtime_engine.js:183 Fetch API cannot load file://runtime-engine/web/runtime_engine_bg.wasm. URL scheme must be "http" or "https" for CORS request.
init @ runtime_engine.js:183
runtime_engine.js:57 Uncaught TypeError: Cannot read property 'load_resource_to_js' of undefined
    at load_resource_to_js (runtime_engine.js:57)
    at eval (osc_runtime_web.js:23)
    at Module../src/osc_runtime_web.js (index.js:109)
    at __webpack_require__ (index.js:20)
    at index.js:84
    at index.js:87
runtime_engine.js:183 Uncaught (in promise) TypeError: Failed to fetch
    at init (runtime_engine.js:183)
    at eval (osc_runtime_web.js:10)
    at Module../src/osc_runtime_web.js (index.js:109)
    at __webpack_require__ (index.js:20)
    at index.js:84
    at index.js:87
```

Here are some changed files:

* webpack.config.js
```js
const path = require('path');
const HtmlWebpackPlugin = require('html-webpack-plugin');

module.exports = {
    entry: "./src/osc_runtime_web.js",
    output: {
        path: path.resolve(__dirname, "dist"),
        filename: "index.js",
    },
    mode: "development",
    module: {
        rules: [{
                test: /\.m?js$/,
                exclude: /(node_modules|bower_components)/,
                use: {
                    loader: 'babel-loader',
                    options: {
                        presets: ['@babel/preset-env'],
                        plugins: ['@babel/plugin-syntax-import-meta']
                    }
                }
            },
            {
                test: /\.js$/,
                loader: require.resolve('@open-wc/webpack-import-meta-loader'),
            }
        ]
    },
    plugins: [
        new HtmlWebpackPlugin({
            template: 'index.html'
        })
    ]
};
```

* src/osc_runtime_web.js
```js
import init, { load_resource_to_js } from "../runtime-engine/web/runtime_engine.js";

init();

var data = {
    kind: "ComputeResource",
    metadata: {
        operation: "create",
        cloud_provider: "hwcloud",
        labels: "test"
    },
    spec: {
        name: "nothing",
        size: 1
    }
};
var output = load_resource_to_js(data);
console.log(output);
```

### Backup

Here are some files generated by `webpack`:

* dist/index.html
```html
<!DOCTYPE html>
<html>

<head>
    <title>osc-serverless</title>
    <meta content="text/html;charset=utf-8" http-equiv="Content-Type" />
</head>

<body>
    <h1>OSC Serverless Demo</h1>

    <p id="demo">JavaScript 可以触发事件，就像按钮点击。</p>

    <script type="text/javascript">
        function run() {
            document.getElementById("demo").innerHTML = "hello world";
        }
    </script>

    <button type="button" onclick="run()">确认</button>

<script type="text/javascript" src="index.js"></script></body>

</html>
```

* dist/index.js
```js
/******/ (function(modules) { // webpackBootstrap
/******/ 	// The module cache
/******/ 	var installedModules = {};
/******/
/******/ 	// The require function
/******/ 	function __webpack_require__(moduleId) {
/******/
/******/ 		// Check if module is in cache
/******/ 		if(installedModules[moduleId]) {
/******/ 			return installedModules[moduleId].exports;
/******/ 		}
/******/ 		// Create a new module (and put it into the cache)
/******/ 		var module = installedModules[moduleId] = {
/******/ 			i: moduleId,
/******/ 			l: false,
/******/ 			exports: {}
/******/ 		};
/******/
/******/ 		// Execute the module function
/******/ 		modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);
/******/
/******/ 		// Flag the module as loaded
/******/ 		module.l = true;
/******/
/******/ 		// Return the exports of the module
/******/ 		return module.exports;
/******/ 	}
/******/
/******/
/******/ 	// expose the modules object (__webpack_modules__)
/******/ 	__webpack_require__.m = modules;
/******/
/******/ 	// expose the module cache
/******/ 	__webpack_require__.c = installedModules;
/******/
/******/ 	// define getter function for harmony exports
/******/ 	__webpack_require__.d = function(exports, name, getter) {
/******/ 		if(!__webpack_require__.o(exports, name)) {
/******/ 			Object.defineProperty(exports, name, { enumerable: true, get: getter });
/******/ 		}
/******/ 	};
/******/
/******/ 	// define __esModule on exports
/******/ 	__webpack_require__.r = function(exports) {
/******/ 		if(typeof Symbol !== 'undefined' && Symbol.toStringTag) {
/******/ 			Object.defineProperty(exports, Symbol.toStringTag, { value: 'Module' });
/******/ 		}
/******/ 		Object.defineProperty(exports, '__esModule', { value: true });
/******/ 	};
/******/
/******/ 	// create a fake namespace object
/******/ 	// mode & 1: value is a module id, require it
/******/ 	// mode & 2: merge all properties of value into the ns
/******/ 	// mode & 4: return value when already ns object
/******/ 	// mode & 8|1: behave like require
/******/ 	__webpack_require__.t = function(value, mode) {
/******/ 		if(mode & 1) value = __webpack_require__(value);
/******/ 		if(mode & 8) return value;
/******/ 		if((mode & 4) && typeof value === 'object' && value && value.__esModule) return value;
/******/ 		var ns = Object.create(null);
/******/ 		__webpack_require__.r(ns);
/******/ 		Object.defineProperty(ns, 'default', { enumerable: true, value: value });
/******/ 		if(mode & 2 && typeof value != 'string') for(var key in value) __webpack_require__.d(ns, key, function(key) { return value[key]; }.bind(null, key));
/******/ 		return ns;
/******/ 	};
/******/
/******/ 	// getDefaultExport function for compatibility with non-harmony modules
/******/ 	__webpack_require__.n = function(module) {
/******/ 		var getter = module && module.__esModule ?
/******/ 			function getDefault() { return module['default']; } :
/******/ 			function getModuleExports() { return module; };
/******/ 		__webpack_require__.d(getter, 'a', getter);
/******/ 		return getter;
/******/ 	};
/******/
/******/ 	// Object.prototype.hasOwnProperty.call
/******/ 	__webpack_require__.o = function(object, property) { return Object.prototype.hasOwnProperty.call(object, property); };
/******/
/******/ 	// __webpack_public_path__
/******/ 	__webpack_require__.p = "";
/******/
/******/
/******/ 	// Load entry module and return exports
/******/ 	return __webpack_require__(__webpack_require__.s = "./src/osc_runtime_web.js");
/******/ })
/************************************************************************/
/******/ ({

/***/ "./runtime-engine/web/runtime_engine.js":
/*!**********************************************!*\
  !*** ./runtime-engine/web/runtime_engine.js ***!
  \**********************************************/
/*! exports provided: load_resource_to_js, default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
eval("__webpack_require__.r(__webpack_exports__);\n/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, \"load_resource_to_js\", function() { return load_resource_to_js; });\nfunction getAbsoluteUrl(relativeUrl) {\n  var publicPath = __webpack_require__.p;\n  var url = '';\n\n  if (!publicPath || publicPath.indexOf('://') < 0) {\n    url += \"\".concat(window.location.protocol, \"//\").concat(window.location.host);\n  }\n\n  if (publicPath) {\n    url += publicPath;\n  } else {\n    url += '//';\n  }\n\n  return url + relativeUrl;\n}\n\nvar wasm;\nvar heap = new Array(32);\nheap.fill(undefined);\nheap.push(undefined, null, true, false);\nvar stack_pointer = 32;\n\nfunction addBorrowedObject(obj) {\n  if (stack_pointer == 1) throw new Error('out of js stack');\n  heap[--stack_pointer] = obj;\n  return stack_pointer;\n}\n\nfunction getObject(idx) {\n  return heap[idx];\n}\n\nvar heap_next = heap.length;\n\nfunction dropObject(idx) {\n  if (idx < 36) return;\n  heap[idx] = heap_next;\n  heap_next = idx;\n}\n\nfunction takeObject(idx) {\n  var ret = getObject(idx);\n  dropObject(idx);\n  return ret;\n}\n/**\n* @param {any} value\n* @returns {any}\n*/\n\n\nfunction load_resource_to_js(value) {\n  try {\n    var ret = wasm.load_resource_to_js(addBorrowedObject(value));\n    return takeObject(ret);\n  } finally {\n    heap[stack_pointer++] = undefined;\n  }\n}\nvar WASM_VECTOR_LEN = 0;\nvar cachedTextEncoder = new TextEncoder('utf-8');\nvar cachegetUint8Memory = null;\n\nfunction getUint8Memory() {\n  if (cachegetUint8Memory === null || cachegetUint8Memory.buffer !== wasm.memory.buffer) {\n    cachegetUint8Memory = new Uint8Array(wasm.memory.buffer);\n  }\n\n  return cachegetUint8Memory;\n}\n\nvar passStringToWasm;\n\nif (typeof cachedTextEncoder.encodeInto === 'function') {\n  passStringToWasm = function passStringToWasm(arg) {\n    var size = arg.length;\n\n    var ptr = wasm.__wbindgen_malloc(size);\n\n    var offset = 0;\n    {\n      var mem = getUint8Memory();\n\n      for (; offset < arg.length; offset++) {\n        var code = arg.charCodeAt(offset);\n        if (code > 0x7F) break;\n        mem[ptr + offset] = code;\n      }\n    }\n\n    if (offset !== arg.length) {\n      arg = arg.slice(offset);\n      ptr = wasm.__wbindgen_realloc(ptr, size, size = offset + arg.length * 3);\n      var view = getUint8Memory().subarray(ptr + offset, ptr + size);\n      var ret = cachedTextEncoder.encodeInto(arg, view);\n      offset += ret.written;\n    }\n\n    WASM_VECTOR_LEN = offset;\n    return ptr;\n  };\n} else {\n  passStringToWasm = function passStringToWasm(arg) {\n    var size = arg.length;\n\n    var ptr = wasm.__wbindgen_malloc(size);\n\n    var offset = 0;\n    {\n      var mem = getUint8Memory();\n\n      for (; offset < arg.length; offset++) {\n        var code = arg.charCodeAt(offset);\n        if (code > 0x7F) break;\n        mem[ptr + offset] = code;\n      }\n    }\n\n    if (offset !== arg.length) {\n      var buf = cachedTextEncoder.encode(arg.slice(offset));\n      ptr = wasm.__wbindgen_realloc(ptr, size, size = offset + buf.length);\n      getUint8Memory().set(buf, ptr + offset);\n      offset += buf.length;\n    }\n\n    WASM_VECTOR_LEN = offset;\n    return ptr;\n  };\n}\n\nvar cachegetInt32Memory = null;\n\nfunction getInt32Memory() {\n  if (cachegetInt32Memory === null || cachegetInt32Memory.buffer !== wasm.memory.buffer) {\n    cachegetInt32Memory = new Int32Array(wasm.memory.buffer);\n  }\n\n  return cachegetInt32Memory;\n}\n\nvar cachedTextDecoder = new TextDecoder('utf-8');\n\nfunction getStringFromWasm(ptr, len) {\n  return cachedTextDecoder.decode(getUint8Memory().subarray(ptr, ptr + len));\n}\n\nfunction addHeapObject(obj) {\n  if (heap_next === heap.length) heap.push(heap.length + 1);\n  var idx = heap_next;\n  heap_next = heap[idx];\n  heap[idx] = obj;\n  return idx;\n}\n\nfunction init(module) {\n  if (typeof module === 'undefined') {\n    module = {\n      url: getAbsoluteUrl('runtime-engine/web/runtime_engine.js')\n    }.url.replace(/\\.js$/, '_bg.wasm');\n  }\n\n  var result;\n  var imports = {};\n  imports.wbg = {};\n\n  imports.wbg.__wbindgen_json_serialize = function (arg0, arg1) {\n    var ret = JSON.stringify(getObject(arg1));\n    var ret0 = passStringToWasm(ret);\n    var ret1 = WASM_VECTOR_LEN;\n    getInt32Memory()[arg0 / 4 + 0] = ret0;\n    getInt32Memory()[arg0 / 4 + 1] = ret1;\n  };\n\n  imports.wbg.__wbindgen_json_parse = function (arg0, arg1) {\n    var ret = JSON.parse(getStringFromWasm(arg0, arg1));\n    return addHeapObject(ret);\n  };\n\n  if (typeof URL === 'function' && module instanceof URL || typeof module === 'string' || typeof Request === 'function' && module instanceof Request) {\n    var response = fetch(module);\n\n    if (typeof WebAssembly.instantiateStreaming === 'function') {\n      result = WebAssembly.instantiateStreaming(response, imports)[\"catch\"](function (e) {\n        return response.then(function (r) {\n          if (r.headers.get('Content-Type') != 'application/wasm') {\n            console.warn(\"`WebAssembly.instantiateStreaming` failed because your server does not serve wasm with `application/wasm` MIME type. Falling back to `WebAssembly.instantiate` which is slower. Original error:\\n\", e);\n            return r.arrayBuffer();\n          } else {\n            throw e;\n          }\n        }).then(function (bytes) {\n          return WebAssembly.instantiate(bytes, imports);\n        });\n      });\n    } else {\n      result = response.then(function (r) {\n        return r.arrayBuffer();\n      }).then(function (bytes) {\n        return WebAssembly.instantiate(bytes, imports);\n      });\n    }\n  } else {\n    result = WebAssembly.instantiate(module, imports).then(function (result) {\n      if (result instanceof WebAssembly.Instance) {\n        return {\n          instance: result,\n          module: module\n        };\n      } else {\n        return result;\n      }\n    });\n  }\n\n  return result.then(function (_ref) {\n    var instance = _ref.instance,\n        module = _ref.module;\n    wasm = instance.exports;\n    init.__wbindgen_wasm_module = module;\n    return wasm;\n  });\n}\n\n/* harmony default export */ __webpack_exports__[\"default\"] = (init);\n\n//# sourceURL=webpack:///./runtime-engine/web/runtime_engine.js?");

/***/ }),

/***/ "./src/osc_runtime_web.js":
/*!********************************!*\
  !*** ./src/osc_runtime_web.js ***!
  \********************************/
/*! no exports provided */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
eval("__webpack_require__.r(__webpack_exports__);\n/* harmony import */ var _runtime_engine_web_runtime_engine_js__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ../runtime-engine/web/runtime_engine.js */ \"./runtime-engine/web/runtime_engine.js\");\n // var OpenServiceCloudApi = import('../autogenerated/js-client/src/index');\n// var defaultClient = OpenServiceCloudApi.ApiClient.instance;\n// // Configure HTTP basic authorization: basicAuth\n// var basicAuth = defaultClient.authentications['basicAuth'];\n// basicAuth.username = 'YOUR USERNAME'\n// basicAuth.password = 'YOUR PASSWORD'\n\nObject(_runtime_engine_web_runtime_engine_js__WEBPACK_IMPORTED_MODULE_0__[\"default\"])();\nvar data = {\n  kind: \"ComputeResource\",\n  metadata: {\n    operation: \"create\",\n    cloud_provider: \"hwcloud\",\n    labels: \"test\"\n  },\n  spec: {\n    name: \"nothing\",\n    size: 1\n  }\n};\nvar output = Object(_runtime_engine_web_runtime_engine_js__WEBPACK_IMPORTED_MODULE_0__[\"load_resource_to_js\"])(data);\nconsole.log(output);\nvar jsonData = JSON.stringify(output); // var callback = function(error, data, response) {\n//     if (error) {\n//       console.error(error);\n//     } else {\n//       console.log('API called successfully. Returned data: ' + data);\n//     }\n// };\n// switch (output.kind) {\n//     case 'ComputeResource':\n//         var api = new OpenServiceCloudApi.ComputeApi();\n//         switch (output.operation) {\n//             case 'create':\n//                 var computeResourceCreateRequest = new OpenServiceCloudApi.ComputeResourceCreateRequest(); // {ComputeResourceCreateRequest} parameters for the requested compute resource.\n//                 computeResourceCreateRequest = JSON.parse(jsonData);\n//                 api.computeResourceCreate(computeResourceCreateRequest, callback);\n//                 break;\n//             case \"delete\":\n//                 api.computeResourceDelete(output.crId, output.cloud_provider, {}, callback);\n//                 break;\n//             default:\n//                 break;\n//         };\n//         break;\n//     default:\n//         break;\n// }\n// var f = document.getElementById('test-file-upload');\n// var filename = f.value; // 'C:\\fakepath\\test.png'\n// if (!filename || !(filename.endsWith('.jpg') || filename.endsWith('.png') || filename.endsWith('.gif'))) {\n//     alert('Can only upload image file.');\n//     return false;\n// }\n\n//# sourceURL=webpack:///./src/osc_runtime_web.js?");

/***/ })

/******/ });
```

**Comment by alexcrichton** [comment] 2019-09-04 16:48
@leonwanghui this is unfortunately a pretty sprawling bug report with a lot of stuff going on, can you try slimming this down to something we can investigate?

**Comment by leonwanghui** [comment] 2019-09-05 00:50
Sorry for the mess, I was debugging yesterday and found that Chrome doesn't support uploading local file to the browser, so the `init()` method failed with the error `Fetch API cannot load file://runtime-engine/web/runtime_engine_bg.wasm. URL scheme must be "http" or "https" for CORS request`.
![image](https://user-images.githubusercontent.com/24707117/64303344-403b3700-cfba-11e9-92be-c8e18d0d50c6.png)

**Comment by Pauan** [comment] 2019-09-06 03:46
This looks like a duplicate of https://github.com/rustwasm/wasm-bindgen/issues/261, the solution is [here](https://github.com/rustwasm/wasm-bindgen/issues/261#issuecomment-528695466).

This will also be solved by `wasm-pack serve`, which will use its own local server.

**Comment by Pauan** [comment] 2019-09-06 03:50
(Since it looks like you're using Webpack, you can use [`webpack-dev-server`](https://webpack.js.org/guides/development/#using-webpack-dev-server) which creates a local server and even has auto-reloading)

**Comment by leonwanghui** [comment] 2019-09-06 04:59
@Pauan Very thanks for your suggestion, and the errors have been gone!

But unfortunately it comes with other errors below:
```shell
runtime_engine.js:57 Uncaught TypeError: Cannot read property 'load_resource_to_js' of undefined
    at load_resource_to_js (runtime_engine.js:57)
    at eval (osc_runtime_web.js:18)
    at Module../src/osc_runtime_web.js (index.js:97)
    at __webpack_require__ (index.js:20)
    at index.js:84
    at index.js:87
``` 

It seems that the js code still can't recognize the compiled function, any suggestions?

**Comment by leonwanghui** [comment] 2019-09-09 11:01
It seems that the error is still here, I don't know if it's caused from webpack config, so I paste my [webpack.config.js](https://github.com/leonwanghui/osc-serverless/blob/master/osc-runtime-js/webpack.config.js) here.

**Comment by leonwanghui** [comment] 2019-09-09 11:07
This is the screencut for the errors.
![image](https://user-images.githubusercontent.com/24707117/64526118-0c06a400-d335-11e9-8590-5ba508a84eb2.png)

**Comment by Pauan** [comment] 2019-09-09 11:14
@leonwanghui It looks like you're [post-processing the files](https://github.com/leonwanghui/osc-serverless/blob/c35a92e383424759045e8d62957e16b50e4b1db7/osc-runtime-js/runtime-engine/build.sh#L10-L14), does it work if you don't do that?

**Comment by leonwanghui** [comment] 2019-09-09 11:43
@Pauan No, the error is the same : (

**Comment by leonwanghui** [comment] 2019-09-10 11:12
Hi, I have solved the problem by switching the target from `web` to `bundler`, and now I want to build a frontend service which needs to access backend service, but it seems that the `webpack-dev-server` doesn't support CORS so I have to build the service based on `nginx` to enable port transporting, but now I got an error below:
![image](https://user-images.githubusercontent.com/24707117/64609111-bbf41400-d3fe-11e9-9166-42dccee863f1.png)

So does that mean currently `webpack-dev-server` is the only way to perform the loading operation for wasm file? If so, is there some way to enable port transport? Thanks!

**Comment by Pauan** [comment] 2019-09-10 18:49
@leonwanghui Any web server will work (as long as the server has support for the `application/wasm` MIME type).

For example, you can do [`cargo install https`](https://crates.io/crates/https) and then run `http` and your code will be at `http://localhost:8080`

But `https` isn't a production server, so you should only use it for development. So you'll need to adjust your production server so that it sends the `application/wasm` MIME type.

[Here is an example](https://gist.github.com/WesThorburn/62ea13952749d6563ce2fb15b45f1ba8) of what you need to do to enable `application/wasm` with Apache and Nginx.

As for `webpack-dev-server` and CORS, you can try something [like this](https://stackoverflow.com/a/44748420).

**Comment by ashleygwilliams** [comment] 2020-01-13 20:47
hi @leonwanghui! it seems that @Pauan has provided a helpful solution for you- and as a result i am going to close this issue. if you are still having trouble please open a new issue!

**Closed by ashleygwilliams** 2020-01-13 20:47 UTC
