### ISSUE TITLE
indicatif bug causes lack of output on msys and potentially other shells

### ISSUE THREAD

**Issue by fitzgen** [rustwasm/wasm-pack#284] opened 2018-09-07 18:16 UTC
Until https://github.com/mitsuhiko/indicatif/issues/60 is fixed, we should probably stop using indicatif in wasm-pack, because it completely breaks the experience for a large swath of windows users.

**Comment by ashleygwilliams** [comment] 2018-09-07 18:56
i would prefer a solution that gracefully degrades for consoles we know we can't support. @alexcrichton says that cargo does this in many areas so we can use that as an example. i would prefer that solution to simply removing the progressbar entirely.

**Comment by alexcrichton** [comment] 2018-09-09 18:10
Digging more into https://github.com/mitsuhiko/indicatif/issues/60 *only* using `indicatif` seems like it suffers another bug, printing zero output when output is piped somewhere else. I believe that means if you try to pipe `wasm-pack` output to a log file, for example, then nothing will get printed at all. That I believe is also quite serious and in need of fixing, although I don't know whether that's classified as another `indicatif` bug or an `indicatif` feature.

**Comment by ashleygwilliams** [comment] 2018-09-20 16:46
this should be remedied by by the update to the console crate which will be handled by #319

**Comment by alexcrichton** [comment] 2018-09-20 17:14
Ah unfortunately the issue isn't 100% fixed from wasm-pack's perspective I think. There's still two issues I believe:

* First is that the output on MSYS2 is unfortunately still not great. I suspect this is a bug still in either `indicatif` or `console`, but the progress bar doesn't update the current line but rather updates the next line:
 
```
| [1/8] Checking crate configuration...
  [1/8] Checking crate configuration...
| [2/8] Adding WASM target...
  [2/8] Adding WASM target...
| [3/8] Compiling to WASM...
\ [3/8] Compiling to WASM...
- [3/8] Compiling to WASM...
/ [3/8] Compiling to WASM...
| [3/8] Compiling to WASM...
\ [3/8] Compiling to WASM...
- [3/8] Compiling to WASM...
/ [3/8] Compiling to WASM...
| [3/8] Compiling to WASM...
\ [3/8] Compiling to WASM...
- [3/8] Compiling to WASM...
/ [3/8] Compiling to WASM...
| [3/8] Compiling to WASM...
\ [3/8] Compiling to WASM...
- [3/8] Compiling to WASM...
/ [3/8] Compiling to WASM...
| [3/8] Compiling to WASM...
\ [3/8] Compiling to WASM...
- [3/8] Compiling to WASM...
/ [3/8] Compiling to WASM...
| [3/8] Compiling to WASM...
\ [3/8] Compiling to WASM...
- [3/8] Compiling to WASM...
/ [3/8] Compiling to WASM...
| [3/8] Compiling to WASM...
\ [3/8] Compiling to WASM...
- [3/8] Compiling to WASM...
/ [3/8] Compiling to WASM...
| [3/8] Compiling to WASM...
\ [3/8] Compiling to WASM...
- [3/8] Compiling to WASM...
```

* There's still a bug with wasm-pack (not indicatif) that when indicatif is turned off due to stderr not being a tty then no output comes out. For example `wasm-pack build 2>&1 | tee out.log` provides no output. (this is something that wasm-pack will need to handle, not indicatif I believe)

**Comment by alexcrichton** [comment] 2018-09-20 17:16
I've opened https://github.com/mitsuhiko/indicatif/issues/62 for the indicatif/console bug

**Comment by c-edw** [comment] 2018-11-12 18:38
Development seems to be very slow on Indicatif, or it's abandoned. I think you might want to consider an alternative.

**Comment by mitsuhiko** [comment] 2018-11-23 09:46
@c-edw I would love to get help maintaining it. It's very actively used i just don't have too many issues with it that I update it regularly.

**Comment by dbrgn** [comment] 2019-02-16 22:18
It also causes issues when running tests in CI (e.g. CircleCI) with stdout-capturing:

![img](https://tmp.dbrgn.ch/screenshots/20190216231712-y0lgetxg.png)

Is there a way to turn that off? Is there some sort of "interactive shell" detection that fails in this case?

**Comment by mitsuhiko** [comment] 2019-02-16 22:39
That is a different issue. I fixed msys support a while back so it prints now.

**Comment by dbrgn** [comment] 2019-02-16 22:50
@mitsuhiko you're right. And wasm-pack uses version 0.9 (released in January). So I guess this issue could probably be closed?

**Comment by ashleygwilliams** [comment] 2019-02-22 17:32
we are now tracking this via #298

**Closed by ashleygwilliams** 2019-02-22 17:32 UTC
Labels: bug
