### ISSUE TITLE
getting started instructions give error with exit code 101

### ISSUE THREAD

**Issue by mvolkmann** [rustwasm/wasm-pack#975] opened 2021-02-16 01:53 UTC
## 🐛 Bug description
I'm following the Quickstart instructions here: https://rustwasm.github.io/wasm-pack/book/quickstart.html.
I installed wasp-pack with:

```bash
curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
```

Then I entered `wasm-pack new hello-wasm` and got this:

```bash
[INFO]: ⬇️  Installing cargo-generate...
error: the `--vers` provided, `latest`, is not a valid semver version: cannot parse 'latest' as a semver

Error: Installing cargo-generate with cargo
Caused by: failed to execute `cargo install`: exited with exit code: 101
```

#### 🤔 Expected Behavior

It should create a new wash-pack project.

#### 👟 Steps to reproduce

See above.

#### 🌍 Your environment

wasm-pack version: 0.9.1
rustc version: 1.50.0

**Comment by ThePuzzlemaker** [comment] 2021-02-16 22:11
Possible duplicate of #907

**Closed** 2021-06-17 19:29 UTC
