### ISSUE TITLE
Remove icons from wasm-pack terminal command output

### ISSUE THREAD

**Issue by ivmazurenko** [rustwasm/wasm-pack#715] opened 2019-09-22 13:41 UTC
##  Bug description
Icons in terminal in output of wasm-pack command

####  Expected Behavior
No icons in terminal.

**Comment by drager** [comment] 2019-10-02 16:57
Hey @ibaryshnikov! Can you describe your issue a bit more?

**Comment by ibaryshnikov** [comment] 2019-10-02 17:01
The question was addressed to @ivmazurenko I guess

**Comment by drager** [comment] 2019-10-02 17:05
@ibaryshnikov Oh sorry! Yes, question for @ivmazurenko

**Comment by ibaryshnikov** [comment] 2019-10-20 09:57
It looks like a duplicate of #632

**Closed** 2019-11-10 07:18 UTC
