### ISSUE TITLE
Distribute wasm-pack binary via cargo

### ISSUE THREAD

**Issue by pablosichert** [rustwasm/wasm-pack#746] opened 2019-12-06 06:30 UTC
Hi there!

Would it be possible to distribute the `wasm-pack` binary via `cargo`, instead of requiring users to run [`curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh`](https://rustwasm.github.io/wasm-pack/installer/)?

It would make keeping track of the installation easier and would automatically provide the binary when `wasm-pack` is added as dependency to `cargo.toml`.

Rust [`bindgen`](https://github.com/rust-lang/rust-bindgen) also [distributes](https://rust-lang.github.io/rust-bindgen/command-line-usage.html) via `cargo`.

**Comment by Pauan** [comment] 2019-12-06 09:35
Although it isn't well advertised, you actually *can* do `cargo install wasm-pack`. Of course this will build the binary from source, because Cargo doesn't currently support shipping pre-compiled binaries.

**Comment by PabloSichert** [comment] 2019-12-06 10:28
Oh, I see! I think it would be nice to state this on that page as well: https://rustwasm.github.io/wasm-pack/installer/.

**Comment by Pauan** [comment] 2019-12-06 10:32
@PabloSichert It actually already does, but you have to click on the `display all supported installers` link (that's what I meant by "it isn't well advertised").

Maybe we could just always display it, without requiring a click on the link. @ashleygwilliams what do you think?

**Comment by ashleygwilliams** [comment] 2020-02-08 15:26
i definitely agree that we should not hide the additional installer instrucitons. i would happily accept a pull request for this.

i have had an issue open for this for a long time actually: https://github.com/rustwasm/wasm-pack/issues/355

i'm going to close this a duplicate :)

**Closed by ashleygwilliams** 2020-02-08 15:26 UTC

**Comment by lynn** [comment] 2023-09-08 19:30
I don't think this issue is a duplicate of #355. That one is about which install options to display on the website. This issue is about distributing a wasm-pack binary via cargo.

Four years ago @Pauan commented that

> Cargo doesn't currently support shipping pre-compiled binaries

but I'm not sure if that's still true (I'm reminded of the recent situation surrounding serde_derive).

**Comment by Pauan** [comment] 2023-09-08 20:11
> but I'm not sure if that's still true (I'm reminded of the recent situation surrounding serde_derive).

It's still true today, you can't ship pre-compiled binaries with Cargo, `cargo install` will always recompile the program from scratch.

https://github.com/rust-cli/team/issues/8

https://github.com/rust-cli/team/issues/20

So the current best way to distribute binaries is to use GitHub Releases (which is [what wasm-bindgen does](https://github.com/rustwasm/wasm-bindgen/releases)).
