### ISSUE TITLE
failed to read target/wasm32-unknown-unknown/release/project.wasm

### ISSUE THREAD

**Issue by huangjj27** [rustwasm/wasm-pack#414] opened 2018-10-15 13:28 UTC
## 🐛 Bug description
when I try to fix #390, I found something strange as described  in https://github.com/rustwasm/wasm-bindgen/issues/962, so I just use [this project](https://github.com/huangjj27/wasm-pack), just changing `CARGO_TARGET_DIR` and reproduce the issue again.

#### 🤔 Expected Behavior
even if `CARGO_TARGET_DIR` is overwritten, wasm-pack and wasm-bindgen should also find the target artifacts

#### 👟 Steps to reproduce
1. open my powershell on windows, working directory at `path\to\project\wasm-pack-learn`
2. set variable: `$env:CARGO_TARGET_DIR="path\to\project\wasm-pack-learn\wasm-pack-target"`
3. run `wasm-pack build`

then, it runs into the issues as https://github.com/rustwasm/wasm-bindgen/issues/962:
```
error: failed to read `target/wasm32-unknown-unknown/release/js_hello_world.wasm`
	caused by: 系统找不到指定的路径。 (os error 3)      # system can't find the path
```

4. set variable: `$env:CARGO_TARGET_DIR="path\to\project\wasm-pack-learn\wasm-pack-learn\inner-target"`, run `wasm-pack build` again. it reproduce the issue.

5. cargo clean
6. build with `cargo build --target=wasm32-unknown-unknown`, it pass

#### 🌍 Your environment
Include the relevant details of your environment.
wasm-pack version: wasm-pack 0.5.0
rustc version: rustc 1.31.0-nightly (2c2e2c57d 2018-10-12)

**Comment by RReverser** [comment] 2018-11-30 13:23
@huangjj27 Why did you close this issue? I just ran into the same, and it doesn't seem to be fixed (except in your commits in a fork).

**Comment by huangjj27** [comment] 2018-11-30 13:50
@RReverser I closed this because I couldn't reproduce it. Reopening for you.

**Comment by RReverser** [comment] 2018-11-30 13:51
Thanks!

**Closed** 2018-11-30 13:54 UTC
Labels: bug, to-do, user report

**Comment by crackcomm** [comment] 2018-12-15 19:54
I installed from the master and indeed the issue is fixed, thanks!
