### ISSUE TITLE
Incorrect package.json generated

### ISSUE THREAD

**Issue by rllola** [rustwasm/wasm-pack#854] opened 2020-06-01 12:00 UTC
### Describe the Bug

I believe the package.json generated is missing a file in `files` when the target is `browser`.

### Expected Behavior

I expect to have a `filecoin_signer_wasm_bg.js`
```
 "files": [
    "filecoin_signer_wasm_bg.wasm",
    "filecoin_signer_wasm.js",
    "filecoin_signer_wasm_bg.js"
  ],
```

### Actual Behavior

What I actually have 
```
  "files": [
    "filecoin_signer_wasm_bg.wasm",
    "filecoin_signer_wasm.js"
  ],
```

### Additional Context

Then when publising to npm I am missing this file.

**Comment by Pauan** [comment] 2020-06-04 05:09
Thanks for the report, this is a duplicate of https://github.com/rustwasm/wasm-pack/issues/837

**Closed by Pauan** 2020-06-04 05:09 UTC

**Comment by lalberge** [comment] 2020-10-08 16:13
You seemed to have close both issues while not fixing any by reporting :)

**Comment by Pauan** [comment] 2020-10-08 16:29
@lalberge The issue was closed because it was fixed. But I can't do a release because only @ashleygwilliams has permission to do that, and she has gone missing.
