### ISSUE TITLE
no prebuilt wasm-opt binaries error

### ISSUE THREAD

**Issue by JHBonarius** [rustwasm/wasm-pack#913] opened 2020-09-07 15:10 UTC
## 🐛 Bug description
I'm running wasm-pack on a raspberry pie 3b (arm v71). and are trying the game of life tutorial. Build 'fails' with an error. (I say 'fails', as I get something that works after all.)

`~/rust/wasm-game-of-life $ wasm-pack build
[INFO]: Checking for the Wasm target...
[INFO]: Compiling to Wasm...
    Finished release [optimized] target(s) in 0.50s
[INFO]: Installing wasm-bindgen...
Error: no prebuilt wasm-opt binaries are available for this platform: Unrecognized target!
To disable `wasm-opt`, add `wasm-opt = false` to your package metadata in your 'Cargo.toml'.`

#### 🤔 Expected Behavior
Looking at `wasm-opt.rs`, I would have expected the build to successfully complete, giving the message "Skipping wasm-opt because it is not supported on this platform".
It also doesn't seem to look for a local wasm-opt in the path, as described above `pub fn find_wasm_opt`. I downloaded the [wasm-opt source](https://github.com/WebAssembly/binaryen), build it locally and added the bin dir it to the path... source doesn't show any signs of looking at the path...

#### 👟 Steps to reproduce
Get a raspberry pie, install raspbian OS, install git, rust, wasm, etc
git clone https://github.com/rustwasm/wasm_game_of_life.git
cd wasm_game_of_life/
wasm_pack build

#### 🌍 Your environment
Include the relevant details of your environment.
wasm-pack version: 0.9.1
rustc version: 1.46.0

**Comment by PiepsC** [comment] 2020-09-09 15:29
I ran into a completely different issue with wasm-opt as well which was solved by downgrading to 0.8.1. I reckon that will not solve anything for you considering the lack of binaries.

Have you tried disabling wasm-opt altogether? `To disable `wasm-opt`, add `wasm-opt = false` to your package metadata in your `Cargo.toml`.` Obviously doesn't address the issue here, but perhaps it'll at least allow you to continue.

**Comment by SebastienGllmt** [comment] 2020-09-28 07:00
I think this is a duplicate of https://github.com/rustwasm/wasm-pack/issues/886

**Comment by JHBonarius** [comment] 2020-09-28 07:05
> I think this is a duplicate of #886

No, because that bug occurs when wasm-opt is actually running. In my case, the wasm-opt binaries are not found at all.

**Comment by AntoninPe** [comment] 2020-11-06 21:15
Same issue here with a raspberry-pi 4

everything compiles well but wasm-opt fails.

**Comment by Dygear** [comment] 2020-12-17 01:03
Same problem on an ARM Mac.

**Comment by darkoverlordofdata** [comment] 2021-01-06 00:43
Same problem occurs on 12.2-STABLE FreeBSD 12.2-STABLE GENERIC  amd64

**Comment by mattdamon108** [comment] 2021-01-31 03:44
exactly same issue on m1 Mac. Any resolution?

**Comment by INCHMAN1900** [comment] 2021-02-05 17:00
Running into the same problem: everything but `wasm-opt` works perfectly fine.

`find_wasm_opt` method only check cache folders(like `/Users/user/Library/Caches` on MacOS). If there is no `.wasm-pack`, it try to download from Github.

There are two solutions I think:
1. disable `wasm-opt` and manually do the opt
2. change the `wasm_opt_path` in `wasm-opt.rs` file to the executable path on my machine, then build my own `wasm-pack`

**Comment by adamaho** [comment] 2021-02-16 00:13
I also can't `wasm-pack` the hello world application on an M1 MacBook Air. Hopefully a resolution comes soon :)

**Comment by INCHMAN1900** [comment] 2021-02-22 16:05
> I also can't `wasm-pack` the hello world application on an M1 MacBook Air. Hopefully a resolution comes soon :)

try add
```
[package.metadata.wasm-pack.profile.release]
wasm-opt = false
```
to your Cargo.toml to disable wasm-opt step.

**Comment by JHBonarius** [comment] 2021-03-01 11:35
> 
> 
> > I also can't `wasm-pack` the hello world application on an M1 MacBook Air. Hopefully a resolution comes soon :)
> 
> try add
> 
> ```
> [package.metadata.wasm-pack.profile.release]
> wasm-opt = false
> ```
> 
> to your Cargo.toml to disable wasm-opt step.

That's what the first reply says. But it's not a fix, but a work-around.

**Comment by willmcpherson2** [comment] 2021-03-21 11:50
For M1 users, you can manually run `wasm-opt`.

Disable automatic wasm-opt in your Cargo.toml:

```
[package.metadata.wasm-pack.profile.release]
wasm-opt = false
```

Install standalone wasm-opt binary:

```
brew install binaryen
```

Run it on your built wasm file, for example:

```
wasm-opt -Oz -o out.wasm in.wasm
```

**Comment by titaneric** [comment] 2021-03-25 14:54
I want to build a wasm in a container without any network access. @willmcpherson2 may be a work-around solution to this (pre-installed it), but hope `wasm-pack` can find `wasm-opt` locally without disabling `wasm-opt` in Cargo.toml.

**Comment by INCHMAN1900** [comment] 2021-03-25 16:47
> I want to build a wasm in a container without any network access. @willmcpherson2 may be a work-around solution to this (pre-installed it), but hope `wasm-pack` can find `wasm-opt` locally without disabling `wasm-opt` in Cargo.toml.

change the `wasm_opt_path` in `wasm-opt.rs` to the local executable path in your container(so wasm-pack won't need to download it from internet), then build your own `wasm-pack`.

**Comment by Nessex** [comment] 2021-05-06 12:26
As an alternative to the above, if you would like the `wasm-pack` command to work normally you can install the `wasm-pack` from [this PR](https://github.com/rustwasm/wasm-pack/pull/957) which looks for binaries in your PATH:

```
# By latest commit at time of this comment
cargo install wasm-pack --git https://github.com/bloveless/wasm-pack --rev fee0938c3417dbcd5d72544a8c1981d761590042
```

This allows me to just run `wasm-pack build --target web` without a separate `wasm-opt` stage.

**Comment by Kade-Powell** [comment] 2021-05-13 01:11
yep, same issue here.. starting to regret this M1 Mac purchase

**Comment by tami5** [comment] 2021-06-29 19:00
> As an alternative to the above, if you would like the `wasm-pack` command to work normally you can install the `wasm-pack` from [this PR](https://github.com/rustwasm/wasm-pack/pull/957) which looks for binaries in your PATH. At least, until such a time as the PR is merged:
> 
> ```
> # By latest commit at time of this comment
> cargo install wasm-pack --git https://github.com/bloveless/wasm-pack --rev fee0938c3417dbcd5d72544a8c1981d761590042
> ```
> 
> This allows me to just run `wasm-pack build --target web` without a separate `wasm-opt` stage.
> 
> Note that you'll also need to follow the instructions above to download or build a working `wasm-opt` binary and put it in your PATH.

Which instruction?  where can I download and build `wasm-opt` binary?

M1 mac

Thanks

**Comment by mtiller** [comment] 2021-08-29 02:48
As far as I can tell, the original repo from @bloveless has been made private (or removed).  I presume this is because the changes were merged into the `wasm-pack` code base.  But it doesn't look like the merged version is released yet.  So it is, at least as of today, unclear how we are supposed to solver this problem.  Yes, I could disable wasm-opt, but I'd prefer to use it since I managed to download it with `homebrew`.  Any suggestions?  Anybody know the specific incantation required to install `wasm-pack` (with merged PR) directly from `git`?  I'm new to `cargo`, so I'm not quite sure what I should do.  Or perhaps the merged version has been released and I'm somehow missing something about how to use it?

Any assistance here is appreciated.

**Comment by mtiller** [comment] 2021-08-29 02:55
Just a quick follow up.  I tried something.  I cannot say if it is "correct", but it did seem to work.  Although I should make clear that this installs an **unreleased** version of `wasm-pack`.  Here are the steps I followed to get this working on my M1 Mac:

1. [Install `homebrew`](https://brew.sh/) (most people probably already have this, but just in case).
2. Run `brew install binaryen` (as suggested by @willmcpherson2)
3. Install the unreleased version of `wasm-pack` using: `cargo install wasm-pack --git https://github.com/rustwasm/wasm-pack --rev c9ea9aebbccf5029846a24a6a823b18bb41736c7`
4. Run your build as usual with: `wasm-pack build --target web` (should run without complaint)

If anybody has any reason to think one of these steps is incorrect, please speak up.  I just thought an update was in order since some of the previous instructions seem to be out of date now.  Hopefully the next release of `wasm-pack` will be released soon and people will no longer see this issue (at least on platforms where a binary of `wasm-opt` is available).

Hope that helps.

**Comment by dkozma** [comment] 2021-11-16 15:18
Wanted to follow up to @mtiller's instructions with changes I had to make for my M1 Mac running macOS Monterey. After installing homebrew and running `brew install binaryen`, run the following (Git SHA updated with current HEAD):

```
MACOSX_DEPLOYMENT_TARGET=10.7 cargo install wasm-pack --git https://github.com/rustwasm/wasm-pack --rev ae10c23cc14b79ed37a7be222daf5fd851b9cd0d
```

This sets the deployment target as specified [in this comment](https://github.com/rust-lang/rust/issues/90342#issuecomment-961828276) to resolve the linker issues in Monterey.

**Comment by reinmind** [comment] 2021-11-27 18:53
I think the bug is caused by the binaryen version_90 doesn't have a macos_aarch prebuild release
https://github.com/WebAssembly/binaryen/releases/tag/version_90
I found the predownload link in the file `mod.rs `
```rust
Tool::WasmOpt => {
            Ok(format!(
        "https://github.com/WebAssembly/binaryen/releases/download/{vers}/binaryen-{vers}-{target}.tar.gz",
        vers = "version_90",
        target = target,
            ))
        }
``` 
and 'os-configuration' in `target.rs`
```rust
#![allow(missing_docs)]

pub const LINUX: bool = cfg!(target_os = "linux");
pub const MACOS: bool = cfg!(target_os = "macos");
pub const WINDOWS: bool = cfg!(target_os = "windows");

#[allow(non_upper_case_globals)]
pub const x86_64: bool = cfg!(target_arch = "x86_64");
#[allow(non_upper_case_globals)]
pub const x86: bool = cfg!(target_arch = "x86");
```
It should be solved by a new binaryen osx_aarch64 release

**Comment by d3lm** [comment] 2021-12-03 19:42
I just submitted a PR (#1088) to fix this issue for Apple Sillicon.

**Comment by babldev** [comment] 2021-12-13 21:58
You can test @d3lm's change with:

```sh
cargo install wasm-pack --git https://github.com/d3lm/wasm-pack --rev 713868b204f151acd1989c3f29ff9d3bc944c306
```

It did the trick for me!

**Closed** 2021-12-16 17:43 UTC
Labels: bug, wasm-opt

**Comment by prichardsondev** [comment] 2024-04-15 22:42
Same issue RPI 4 - Bookworm v12 64 Bit

Error: no prebuilt wasm-opt binaries are available for this platform: Unrecognized target!
To disable `wasm-opt`, add `wasm-opt = false` to your package metadata in your `Cargo.toml`.
Caused by: no prebuilt wasm-opt binaries are available for this platform: Unrecognized target!
To disable `wasm-opt`, add `wasm-opt = false` to your package metadata in your `Cargo.toml`.

**Comment by WilfredAlmeida** [comment] 2024-05-12 14:07
Same issue on M3 Mac while running `docker compose up`
