### ISSUE TITLE
Error in Linux installer script

### ISSUE THREAD

**Issue by devconsole** [rustwasm/wasm-pack#1217] opened 2023-01-29 13:33 UTC
## 🐛 Bug description
When running the installer in a terminal under Ubuntu 22.04.1 LTS, the following error gets printed:
sh: 139: [: x86_64: unexpected operator

#### 🤔 Expected Behavior
No error message

#### 👟 Steps to reproduce
curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

#### 🌍 Your environment
Ubuntu 22.04.1 LTS

Line 139 reads:
  if [ "$_cputype" == "aarch64" ] && [ "$_ostype" == "apple-darwin" ]; then

I think this would work instead (similar to the statement in line 101):
  if [ "$_cputype" = "aarch64" -a "$_ostype" = "apple-darwin" ]; then

**Comment by artemromaniv** [comment] 2023-02-21 16:15
i also coudn't install wasm-pack using this shell script, so i installed it using cargo 

`cargo install wasm-pack`

**Comment by socketbox** [comment] 2023-04-23 16:52
Duplicate of #1159

**Closed** 2023-11-19 11:18 UTC
