### ISSUE TITLE
Incorrect package.json generated

### ISSUE THREAD

**Issue by lalberge** [rustwasm/wasm-pack#922] opened 2020-10-08 16:16 UTC
Hello 👍 
You have closed these two issues but I think the issue remains unchanged:

https://github.com/rustwasm/wasm-pack/issues/854
https://github.com/rustwasm/wasm-pack/issues/837

**Describe the Bug**
I believe the package.json generated is missing a file in files when the target is browser.

**Expected Behavior**
I expect to have a filecoin_signer_wasm_bg.js

 "files": [
    "filecoin_signer_wasm_bg.wasm",
    "filecoin_signer_wasm.js",
    "filecoin_signer_wasm_bg.js"
  ],
**Actual Behavior**
What I actually have

  "files": [
    "filecoin_signer_wasm_bg.wasm",
    "filecoin_signer_wasm.js"
  ],
**Additional Context**
Then when publising to npm I am missing this file.

**Comment by pachi** [comment] 2020-10-22 09:01
@lalberge IIRC the issue is fixed but there isn't a published version with the fix.

**Comment by lalberge** [comment] 2020-10-22 09:13
@pachi Thanks for the answer :) Have you any idea of an ETA for the next release?

**Comment by jrop** [comment] 2020-11-17 18:16
As a temporary workaround, I added a `build.sh` script that does the following:

```sh
#!/bin/bash
set -e

wasm-pack build
node <<EOF
const fs = require('fs');

const pkg = require('./pkg/package.json');
pkg.files = fs.readdirSync('./pkg/');
fs.writeFileSync('./pkg/package.json', JSON.stringify(pkg, null, 2));
EOF
```
This (sloppily) updates the `package.json:files` key to include everything in the `pkg/` directory.

**Comment by ashleygwilliams** [comment] 2020-12-21 20:38
this will be fixed when the next version is released which i am hoping to do by the end of the year

**Closed by ashleygwilliams** 2020-12-21 20:38 UTC
